### ISSUE TITLE
the output is always SSH-2.0-Go

### ISSUE THREAD

**Issue by sshuvro58** [antoniomika/sish#106]
I have tried the following command to 
`ssh -R 80:localhost:1337 m.tunnel.domain.net -p 1337` , although there is something running on my port 1337 , but if I visit ` m.tunnel.domain.net ` , I see `SSH-2.0-Go` in the browser . 
I have built my docker image using following command 

```
docker run -itd --name sish \
 -v ~/sish/ssl:/ssl \
 -v ~/sish/keys:/keys \
 -v ~/sish/pubkeys:/pubkeys \
 --net=host antoniomika/sish:latest \
 --ssh-address=:1337 \
 --http-address=:1334 \
 --https-address=:446 \
 --https=false \
 --https-certificate-directory=/ssl \
 --authentication-keys-directory=/pubkeys \
 --private-key-location=/keys/ssh_key \
 --bind-random-ports=false
```

In the server log I see  the following 

**2020/06/29 - 17:47:40 | Accepted SSH connection for: 127.0.0.1:34714
2020/06/29 - 17:47:45 | read tcp 127.0.0.1:1337->127.0.0.1:34714: use of closed network connection**

One more thing , I need to mention , when I run a docker image , I always see on which port it is running like `0.0.0.0:5432->5432/tcp` , but for this image , I can't see any port , although it is up and running

**Comment by antoniomika** [comment]
The reason you can't see the port in the `docker ps` output is because you're running sish with `--net=host`, most likely to allow binding tcp ports on the host interface. Otherwise, when you attempt to bind a remote port on the sish server, you won't be able to access the forwarded port since it is bound to the container ip address.

It looks like the issue you're having here is you're pointing the browser at sish's SSH port, and not the HTTP/HTTPS port. Are you running this ssh command on the machine that hosts sish? If so, you're essentially creating a loop where any requests to sish over http are redirecting to the port 1337, which is the sish ssh port.

**Comment by sshuvro58** [comment]
@antoniomika  No , I am not running that command on machine where ssh is hosted.  The way my server is configured is , anything that hits on 1337 port , will be shown in `*.tunnel.domain.net ` for example `abc.tunnel.telemesh.net` 
I ran the following command  from my local machine

`ssh -R 80:localhost:1337 abc.ssh.domain.net`

but it doesn't work , if I hit the URL , I get the following error in server

Error #01: cannot find connection for host: abc.ssh.domain.net

**Comment by antoniomika** [comment]
You need to request the domain from the ssh forward request. I.e. your ssh command should actually be `ssh -R abc:80:localhost:1337 ssh.domain.net`
