### ISSUE TITLE
Can't transfer large file through SSH Tunneling.

### ISSUE THREAD

**Issue by W3-MajorArif** [antoniomika/sish#115]
Hello Sir,

I've tried to load images hosted on my local server using sish. 

1. Without changing any configuration I got success for small files below 1 MB. But for large files, it shows "Error retrieving keepalive response: EOF" error and the connection forcefully closed by the server.

2. Then I changed "idle-connection-timeout", "ping-client-interval", "ping-client-timeout" values to 20 second. This time connection not closed but I got an "unexpected EOF reading trailer" error. 

3. sometimes I got below error in the docker log.
2020/07/20 14:54:11 [Recovery] 2020/07/20 - 14:54:11 panic recovered:
net/http: abort Handler
/usr/local/go/src/net/http/httputil/reverseproxy.go:307 (0xaa5951)
/go/pkg/mod/github.com/antoniomika/oxy@v1.1.1-0.20200517194743-bedd7c62c77e/forward/fwd.go:564 (0xad246f)
/go/pkg/mod/github.com/antoniomika/oxy@v1.1.1-0.20200517194743-bedd7c62c77e/forward/fwd.go:292 (0xacf979)
/go/pkg/mod/github.com/antoniomika/oxy@v1.1.1-0.20200517194743-bedd7c62c77e/roundrobin/rr.go:147 (0x76b63c)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/utils.go:48 (0xabbaef)
/app/httpmuxer/httpmuxer.go:150 (0xbe394e)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xaa830a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83 (0xabb76f)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xaa830a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/logger.go:241 (0xaba8a0)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xaa830a)
/app/httpmuxer/httpmuxer.go:52 (0xbe27ea)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0xaa830a)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:445 (0xab1ec7)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:438 (0xab1b22)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 (0xab14cc)
/usr/local/go/src/net/http/server.go:2836 (0x6ec192)
/usr/local/go/src/net/http/server.go:1924 (0x6e7afb)
/usr/local/go/src/runtime/asm_amd64.s:1373 (0x463000)

Not sure where do I make a mistake. Can you please sort out the issue here?

Many THanks in advance.

**Comment by antoniomika** [comment]
Hey @W3-MajorArif!

I don't seem to be able to reproduce these issues. Granted, I have `--idle-connection=false` in starting sish. Here is what I tried:

```bash
# Setup a tunnel to a site that has files of various sizes I can try to download
ssh -R foobar:80:ipv4.download.thinkbroadband.com:80 ssi.sh

# Download various file sizes. In the curl output, and verify the status code is 0 after each invocation
curl -vvv --output /dev/null https://foobar.ssi.sh/5MB.zip
echo $?
curl -vvv --output /dev/null https://foobar.ssi.sh/10MB.zip
echo $?
curl -vvv --output /dev/null https://foobar.ssi.sh/1GB.zip
echo $?
```

The main reason to have ping timeouts and idle connection timeouts enabled is to account for poor connectivity that could cause a tunnel to stay alive longer than it should. If this is the case, you might also need to tweak the ping-client-interval and ping-client-timeout in order to best account for your situation. For example, you may want to set your ping-client-timeout to 20s, but the ping-client-interval to 5s, to try and ping the client every 5s, but only close the connection after 20s have passed (about 4 pings). The defaults are set for most use cases where the connection is fast enough (and you want to have a response on whether or not a client has died) as fast as possible.

For you specifically, I'd recommend starting sish with the following:

```
--idle-connection=false --ping-client-interval=5s --ping=client-timeout=20s
```

This will:
1. Disable the timeout for the HTTP connection (image loading)
2. And give the connection ample time to respond to a ping before closing the connection.

Hope this helps.

**Comment by GigaFyde** [comment]
Those additional arguments seem to have resolved my issues with large files
