### ISSUE TITLE
Define bind address for TCP

### ISSUE THREAD

**Issue by blop** [antoniomika/sish#127]
Hello,

I'm testing sish and it looks great at the moment ;-)

I used the following options with a IP+port and it's working fine: 
  --ssh-address
  --http-address
  --https-address

But it seems there is no configuration option to define which IP address to use for the TCP port bindings.
They currently bind 0.0.0.0 which I would like to avoid.

Could we add a --tcp-address or something similar ?

Thanks !

**Comment by blop** [comment]
Actually, the TCP address for the binding is currently using the value provided by the client if any, or 0.0.0.0.
I'd like to force a single TCP address.

**Comment by blop** [comment]
So maybe have a `default TCP address` and a `force default TCP address` flag to allow more use cases.

**Comment by antoniomika** [comment]
I think this is definitely useful to be added and I'll add it in the next release. My thought is it will be used as a default [here](https://github.com/antoniomika/sish/blob/b68d602615ba46eccf00ad600914bf77b7d790e2/utils/utils.go#L460). For now, you can always set `--localhost-as-all=false` to enforce that the user needs to set the correct bind address, otherwise using `localhost` will force it to localhost.

**Comment by blop** [comment]
Great, thank you!

What do you think about having a --force-tcp-bind-address as well ?
I don't want to allow clients to select the bind address actually.

The same way we can restrict alias, ports and subdomains, I think we should allow restricting the TCP bind address(es).

**Comment by pcj** [comment]
Sorry, I'm still confused about this...   I'm starting to play with this (it's awesome by the way!) and have it successfully running behind an nginx-ingress controller in a kubernetes cluster.  For routing packets to the sish service with http/https, it's fine because it is known from `--http-address`, but I need a known port for tcp connections in the same way.  

Is it possible?  ngrok chooses a scheme like `0.tcp.ngrok.io:19234` which is quite different from the generated http URLs, so maybe something is fundamentally different here?

**Comment by antoniomika** [comment]
Using kubernetes adds complexity here as you'll likely need to preselect ports and expose them as NodePorts. The way ngrok does is due to the fact that they handle a "pool" of addresses for a locale. Ports cannot be handled through an ingress similar to how the HTTP endpoints are pulled. Enabling host networking is probably the "best" case. TCP connections establish a new port for each forward. TCP doesn't have a "virtualhost" concept (using SNI or Host header) to figure out where to route a request. Where the requester chooses the port, that's just doing something like:
```
ssh -R 8080:localhost:8080 ssi.sh
```

And then accessing the TCP service using:
```
telnet ssi.sh 8080
```

You can request an interface by using a bind ip as part of the request like:
```
ssh -R 0.0.0.0:8080:localhost:8080 ssi.sh
```
