### ISSUE TITLE
autossh | Connection to .. closed by remote host

### ISSUE THREAD

**Issue by blop** [antoniomika/sish#133]
Hi again ;-)

I'm having some disconnection and I'm not sure why or how to debug that.

On the sish server I have : 
`            --idle-connection-timeout=1h
`
On my client config I have : 
```
Host *
    ServerAliveInterval 30
    ServerAliveCountMax 120

```
I connect through the TCP alias using : 
`ssh -J sishserver user@tcpalias
`

And sometimes I get disconnected even while doing stuff actively, like with a ping running and receiving replies.
Any clue ?

Thank you!

**Comment by blop** [comment]
Note that I only have the issue when using a TCP alias, if I publish a normal TCP port and connect through it, it's stable.

**Comment by antoniomika** [comment]
Hmm, is this failing because autossh isn't able to forward a monitor port? To test, run autossh with `-M0` and see if that solves it.

**Comment by blop** [comment]
Hello,

Indeed, the issue is resolved when using `-M0` on the autossh command. :)

Not sure why it's failing when the monitoring port is enabled.
I get the following output from sish and it works for a while, and no specific error on the autossh side :
`
Starting SSH Forwarding service for tcp:22. Forwarded connections can be accessed via the following methods:                                                                                                                                                                                             
TCP Alias: autossh1:22                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                         
Starting SSH Forwarding service for tcp:40618. Forwarded connections can be accessed via the following methods:                                                                                                                                                                                          
TCP: sishserver:40618                                                                                                                                                                                                                                                                                     
`

Then it's failing with this in the sish server logs : 
`
2020/10/05 - 09:28:56 | Unable to load tcp alias: 127.0.0.1:40618
2020/10/05 - 09:28:56 | Closed SSH connection for: x.y.z.q:34010 user: root
`

Isn't there something to be fixed in sish ?

**Comment by antoniomika** [comment]
The reason for this is autossh uses a pair of local and remote port forwards to monitor the session. Take a look at the source here: https://github.com/jonhiggs/autossh/blob/master/autossh.c#L418

sish doesn't support local port forwarding since that's not really the goal of the project. This, combined with the fact that sish is pretty logical when it pertains to ssh/tcp timeouts, there isn't really a need to fix this use case specifically for the use of autossh. If you are still interested in daemonizing with autossh, you can continue to use it to manage ssh error codes but still use it with the ssh timeouts and intervals. Here's an example:

```
autossh -M 0 -o "ServerAliveInterval 30" -o "ServerAliveCountMax 3" -R 80:localhost:80 ssi.sh
```

Using [ServerAliveInterval](https://man.openbsd.org/ssh_config#ServerAliveInterval) and [ServerAliveCountMax](https://man.openbsd.org/ssh_config#ServerAliveCountMax) combined with sish's conservative timeouts for ping intervals should solve it.

**Comment by blop** [comment]
Ok, Thank you!
