### ISSUE TITLE
Add an example in the wiki for a standard non-Docker systemd script?

### ISSUE THREAD

**Issue by srk** [antoniomika/sish#158]
It would be nice to have an example standard non-Docker systemd script, for the benefit of those running this outside a container.

**Comment by antoniomika** [comment]
Hi @srk,

This would definitely be useful to add. I've just included documentation for things that I use often so it was convenient to do so. Would be happy if someone could take this on!

**Comment by bibo38** [comment]
Here's my setup:

Setup User and compile sish:
```bash
useradd -d /srv/sish -m sish
su sish
cd
mkdir pubkeys
# put your pubkeys into the folder...
# now we download & compile sish
git clone https://github.com/antoniomika/sish.git
cd sish
go build .
```

Create `/etc/systemd/system/sish.service` with the following content:
```ini
[Unit]
Description=sish Tunnels

[Service]
ExecStart=/srv/sish/sish/sish --ssh-address=:1234 --http-address=localhost:2345 --authentication-keys-directory=/srv/sish/pubkeys -d sish.example.com --http-port-override 80 --bind-random-subdomains=false
WorkingDirectory=/srv/sish/sish
User=sish
Group=sish
Restart=on-failure
RestartSec=5s
# Security things, need to be disabled for initial SSH key generation
ProtectSystem=strict
PrivateTmp=true
PrivateDevices=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true

[Install]
WantedBy=multi-user.target
```
And start it via `systemctl start sish`

And as my setup required an reverse ssh proxy, here's a minimal working (only http tested) nginx server block config:
```nginx
server {
    listen       80;
    server_name  *.sish.example.com sish.example.com;

    location / {
        proxy_pass http://127.0.0.1:2345;
        proxy_set_header Host $http_host;
    }
}
```

I can create an PR, but I don't really know if this belongs to the README or a separate file.

**Comment by antoniomika** [comment]
Thanks @bibo38! I'll add this to the wiki!

**Comment by bibo38** [comment]
@antoniomika can I support you closing this issue? Just tested my above description and it still works fine for v2. Just added a minor `exit` to indicate that the following steps need root permissions.

**Comment by antoniomika** [comment]
@bibo38 oh sweet! Let me get this in the wiki and send you a draft (I'll do that now and it should take me a min)

**Comment by bibo38** [comment]
btw. here is my short list of cmds i've used to update (to v2):

```bash
su sish
cd ~/sish
git pull
# just to be safe
rm sish
go build .
# back to the root user
exit
systemctl restart sish
```

**Comment by antoniomika** [comment]
@bibo38 here's the link: https://github.com/antoniomika/sish/wiki/Deployment-with-systemd

**Comment by srk** [comment]
Excellent, will test this soon!

**Comment by bibo38** [comment]
@antoniomika Nice! A few things:
- The curl gets a specific release
  - This is inconsistent to the git command, as this always gets the latest main branch version => just point it out or maybe checkout a tag or release branch
  - Do you wanna update the release url every time in the wiki (as probably most people wanna copy/paste such a long command)? => [With some more bash scripting](https://geraldonit.com/2019/01/15/how-to-download-the-latest-github-repo-release-via-command-line/) you could dynamically get the latest release
  - (the highlighting seems to be broken after the curl. But I think this is more a parsing issue than a broken command)
-  Probably after the `systemd start sish` a `systemd enable sish` should be added, so that sish also starts on boot/after a reboot.
- The sish flags were meant for a reverse proxy in front of sish
  - Either note the user, that he needs to also needs to set up a reverse Apache/Nginx/whatever pointing `sish.example.com` to `localhost:2345`.
  - Change the http and ssh address flags to the default value to be consistent with the docker setup script (e.g. both use the same flags with similar values)
    - This also requires `AmbientCapabilities=CAP_NET_BIND_SERVICE` under the `Services` section, so that sish is allowed to bind ports below 1024: https://stbuehler.de/blog/article/2017/06/23/systemd__allow_normal_process_to_bind_to_privileged_port.html

**Comment by antoniomika** [comment]
@bibo38 you're the best! I just updated the document!

**Comment by bibo38** [comment]
@antoniomika lgtm :+1: @srk maybe you close this issue after your practical test (as it may give some additional feedback/improvements).

**Comment by srk** [comment]
It might take a while for me to get back to this, so I will close the issue now. I will make a new issue if I have any feedback or improvements to suggest .
