### ISSUE TITLE
Can't bind Port 80 and 443 to the same domain

### ISSUE THREAD

**Issue by LeXonJe** [antoniomika/sish#178]
Hey! I am trying to forward Ports 80 and 443 from my Nginx Proxy Manager to another Server via SSH and Sish.

I saw issue #143 which describes exactly the setup I'm trying to do. I already set `--https=false` in my `docker-compose.yml` File so sish doesn't try to re-encrypt. And then I connected to sish via `ssh -p 2222 -R domain:80:localhost:80 -R domain:443:localhost:443 (server ip)`. It binds port 80 with no problem at all. However, for port 443 it says:
> The subdomain (domain) is unavailable. Assigning a random subdomain.

I also use `--redirect-root=false` and `--bind-any-host` so that I can bind to the domain and not to a subdomain (from #167).

How can I force sish to bind Port 443 to the same domain?

Here is my `docker-compose.yml` File for sish in case it's needed:
> version: '3.9'
> services:
>   sish:
>     image: antoniomika/sish:latest
>     restart: unless-stopped
>     network_mode: host
>     volumes:
>       - './sish/ssl:/ssl'
>       - './sish/keys:/keys'
>       - './sish/pubkeys:/pubkeys'
>       - './letsencrypt:/etc/letsencrypt'
>     command: |
>       --ssh-address=:2222
>       --http-address=:80
>       --https-address=:443
>       --https=false
>       --authentication
>       --authentication-keys-directory=/pubkeys
>       --private-key-location=/keys/ssh_key
>       --bind-random-ports=false
>       --bind-random-subdomains=false
>       --domain=(domain)
>       --redirect-root=false
>       --bind-any-host

**Comment by antoniomika** [comment]
Hi @LeXonJe 

What you're trying to do should use TCP forwards rather than HTTP forwards in sish. sish will proxy http/https traffic as part of HTTP forwards to the same backend (ergo, the reason the second forward to 443 fails as the pxoy is enabled there. What you likely want to do is change these two to be random ports so you can request port 80 and 443 as a tcp connection. Also drop the `domain:` from your ssh command:

```
--http-address=:80
--https-address=:443
```

then request your forwards again. If you want to forward the domain with HTTP forwards, you should only need one of the forwards you have in your SSH command.
