### ISSUE TITLE
Configuration Clarifications

### ISSUE THREAD

**Issue by lahma0** [antoniomika/sish#182]
Hello again Antonio, I'm sorry for polluting your 'Issues' section with what are more so questions than actual issues, but I wasn't sure where else to try to get an answer on a few things. If there would be a more appropriate place, let me know.

**Docker Tags: 'latest' vs 'main'**
What is the difference between the 2? My assumption is that 'latest' is the same build as the latest release on 'https://github.com/antoniomika/sish/releases' and that 'main' is a build including the latest commit on the Github. Is this correct? If so, would it be best to stick with 'latest'? If I go with 'main' could some of the configuration parameters and instructions on the main Github page be wrong/out-of-date? I assume all of the information on the Github page correspond only to the 'latest' build and therefore it will be safe to follow those instructions and use any of the listed configuration parameters without fear that they will be missing from the 'latest' build?

**Any Way to Attach to Container and Issue Commands?**
Is there any way to attach to my running sish docker container and get a shell that I can use to issue commands inside of the container (without interrupting sish)? As it is, if I attach to my container, I simply see the log data that is being output to stdout. I'm pretty new to Docker and I was hoping you might be able to give me a quick solution to accomplish this. I've messed around with it for far, far too long... The command I run to spin up my docker container (after I've stopped it for whatever reason) is the following (the '--no-deps' is because I never stop/disturb my letsencrypt container):

    docker-compose -f docker-compose.yml up -d --no-deps --build sish

**Timezone of sish Container and its Logs**
I've noticed that my sish container uses UTC as its time zone and not the time zone of my host system. I understand that this is normal for a docker container but I was hoping you could tell me if the including these last 2 lines in my 'volumes' section of my docker-compose file is the correct way to fix the problem:

    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./pubkeys:/pubkeys
      - ./keys:/keys
      - ./ssl:/ssl
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

**Comment by antoniomika** [comment]
Hey @lahma0!

Sorry for the super long delay here, it dropped off my todo list for some reason. You can always feel free to email me or send me a message over IRC for questions!

1. Docker Tags: 'latest' vs 'main'
You are correct, `latest` is the latest release while `main` is a branch based update. The way I've setup CI for sish and my other projects is each branch is automatically built and pushed up to docker. Helps for my testing as well as I can have others test bug fixes. As a heads up, main will "generally" correspond to latest as I will do dev in a separate branch and PR and merge when ready. There are times when it is out of sync when I'm waiting on another fix to land before drafting a release. I'd suggest sticking to `latest` as it'll result in less of a chance for things to be broken if I bork something. If you want to live on the edge though, `main` should also be okay.

2. Any Way to Attach to Container and Issue Commands?
This is unfortunately not currently possible with sish. sish's docker image uses a [scratch container] (https://github.com/antoniomika/sish/blob/main/Dockerfile#L41) which just bundles its resources rather than other tools such as a shell. If you need to debug something within sish while it is running, you could use the build-cache image (which is much heavier than the actual image) to test, but you need to make sure the entrypoint is the same. This could be very complicated and not worth it though. If you let me know what you're trying to do, I can let you know some ways to get around this.

3. Timezone of sish Container and its Logs
To get this to work, you'd need to also mount `/usr/share/zoneinfo/`. You can also just mount `/usr/share/zoneinfo/` and add an environment variable for the timezone you're in like `TZ=America/New_York`.

Hope this helps.
