### ISSUE TITLE
Port forwarding rtsp cameras (port 554)

### ISSUE THREAD

**Issue by riazbapoo** [antoniomika/sish#195]
I am trying to access my cameras remotely by port forwarding port 554 to port 554 with the following command 
`ssh -R cameras:554:10.0.0.111:554 domain.com`

the output is:
```
Starting SSH Forwarding service for tcp:554. Forwarded connections can be accessed via the following methods:
TCP Alias: cameras:554
```

how do I access the cameras

**Comment by frankhommers** [comment]
You should be able to access domain.com:554 for your cameras. As long as there is a service listening on 10.0.0.111:554

**Comment by antoniomika** [comment]
Hey @riazbapoo,

You need to drop the `cameras:` from your ssh command. When you provide a parameter to a TCP connection, that creates a TCP alias within sish (an unexposed connection). If that is intentional, you can use a local forward `ssh -L 8080:cameras:554 domain.com` and point your rtsp client to localhost:8080. If it supports using a command as a pipe (like ffmpeg) you could even do this with ssh by doing `ssh -W cameras:554 domain.com`.
