### ISSUE TITLE
SSH using macOS Terminal asks for password

### ISSUE THREAD

**Issue by bangbaew** [antoniomika/sish#201]
I'm quite new to this and I want to forward my port to a static url using sish, but it asks for password at si.sh
I've tried using both Docker method and running on my local machine, but I don't know the password, I've tried generating my own ED25519 keypair, but in sish terminal it says **x509: decryption password incorrect**, so may I ask for tutorial about passwords?
<img width="676" alt="image" src="https://user-images.githubusercontent.com/29559559/144452687-f1b83085-21e9-4ae1-9573-9f058950637a.png">

Thanks.

**Comment by mrmc-mc** [comment]
same problem

**Comment by antoniomika** [comment]
Hey @mrmc-mc,

Unfortunately, the instance running at ssi.sh is no longer public. Due to people abusing the service I decided to shut it down. 

I removed the demo info from the README in [this commit](https://github.com/antoniomika/sish/commit/1d9fd85ae333099a9b0cbe586329f15f0d76b1a1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5). Is there another reference I need to cleanup?

Best,
