### ISSUE TITLE
Exposing tcp aliases as socket files

### ISSUE THREAD

**Issue by diseq** [antoniomika/sish#232]
Hi, this is really an awesome project and great work.

Is there the possibility to expose tcp aliases as socket files?

My usecase is, that a program on the server needs to connect to a forwarded tcp connection but does not support something like a proxycommand (e.g. ProxyCommand="ssh -W %h:%p ssi.sh"). However connecting to a socket file is supported.

Local server ports would be an option but tcp aliases might be better readable.

**Comment by antoniomika** [comment]
Hi @diseq,

Thanks for the kind words! Yes, sish does publish the forwarded connections as Unix sockets (I had the same use case as you and gives the added benefit of simple socket programming. The issue is, the sockets are based on the incoming connection (address and port), so it could be difficult to determine these. That being said, the API does publish the location of these files for each listener. I'm AFK for the next few hours but can help provide some documentation when I'm back at a computer. You can also use ssh with local forwarding to open a TCP socket on the local host that has access to the alias (documented [here](https://github.com/antoniomika/sish#tcp-alias-forwarding).

Best,

**Comment by antoniomika** [comment]
The relevant API endpoint is available as so (admin console needs to be enabled):

```bash
curl 'http://sish/_sish/api/clients?x-authorization=[SECRET]'
```

The response looks like:

```json
{
   "clients":{
      "ip:port":{
         "listeners":[
            "/tmp/ip:port:hash"
         ],
         "pubKey":"",
         "pubKeyFingerprint":"",
         "remoteAddr":"ip:port",
         "routeListeners":{
            "httpListeners":{
               
            },
            "listeners":{
               
            },
            "tcpAliases":{
               "addr:aliasport":"/tmp/ip:port:hash"
            }
         },
         "session":"",
         "user":"",
         "version":""
      }
   },
   "status":true
}
```

The socket for the alias is at `clients.ip:port.routeListeners.tcpAliases.aliasaddr:aliasport`. Once you have that address, you can use to to talk to the socket with:

```bash
curl -vvk --unix-socket ./ip:port:224432506363170 https://host/path
```

**Comment by diseq** [comment]
thanks a lot!
bit jq and done...
