### ISSUE TITLE
Feature Request: Support authentication for HTTP/HTTPS request.

### ISSUE THREAD

**Issue by ikeji** [antoniomika/sish#263]
I have a feature request that support authentication for HTTP/HTTPS request.

## Use case
I have few private services inside private networks.
I want to allow access these services from internet.
But I want to open these services only for authorized users.

## Feature request
Have a authentication method (ex, basic auth) when user access to sish before dispatch to service behind of sish.

## Why need this in sish?
One alternative ideas are put authentication proxy in front of sish.
But that proxy need to terminate SSL and we can't use sish's ondemand cert feature.

Other idea is put authentication proxy behind of sish.
But the proxy need to setup for each services.

Thanks,

**Comment by antoniomika** [comment]
This is actually already implemented :)

As long as `--bind-http-auth` is enabled (which is true by default), you can provide a forward such as:

```
ssh -R foo\\:bar@test:80:localhost:80 ssi.sh
```

Where `foo` is the username and `bar` is the password.  This will require that all requests (including to the service console) provide those access credentials in order to access it.

**Comment by ikeji** [comment]
Oh, Nice.
Thanks!!
