### ISSUE TITLE
Improve terminal output formatting

### ISSUE THREAD

**Issue by BenHarris** [antoniomika/sish#47]
1) As noted in #46, could we remove the port if it is the standard 80 or 443
2) Could we remove scrap `Starting SSH Forwarding service for http:80.` as it is essentially repeated when the endpoints are announced
3) Could update `Forwarded connections can be accessed via the following methods:` to `Forwarding HTTP/TCP traffic from:` and colour it and the following lines green? 😄 😆 

So the output would look something like the following (sorry for the misuse of diff formatting haha)
```diff
# Press Ctrl-C to close the session.
+ Forwarding HTTP traffic from:
+ HTTP: http://abc.sish-host.com
+ HTTPS: https://abc.sish-host.com
```

Or even slicker with
```diff
# Press Ctrl-C to close the session.
+ Forwarding HTTP traffic from http://abc.sish-host.com and https://abc.sish-host.com
```

**Comment by antoniomika** [comment]
So the only reason I think I'd like to keep the way things currently are is because you can actually open multiple SSH reverse tunnels, but I definitely understand if that doesn't make sense. I like the idea of cleaning up the format and maybe even adding colored formatting though, so I'll look into what this could look like!

**Comment by antoniomika** [comment]
Closing this, tracking in #42
